#Create a pod called time-check in the dvl1987 namespace. This pod should run a container called time-check that uses the busybox image.
#Create a config map called time-config with the data TIME_FREQ=10 in the same namespace.
#The time-check container should run the command: while true; do date; sleep $TIME_FREQ;done and write the result to the location /opt/time/time-check.log.
#The path /opt/time on the pod should mount a volume that lasts the lifetime of this pod.

## Create new namespace "dvl1987" using imerative commands:
## -- kubectl create namespace dvl1987

## Create POD YAML with imperative command: 
## -- kubectl run --generator=run-pod/v1 time-check --image=busybox --dry-run -o yaml > q3.yml

## Create ConfigMap with imperative command:
## -- kubectl create configmap time-config --from-literal=TIME_FREQ=10

## Once the POD YAML is created, edit it to meet all question requirements
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    resources: {}

## -- args specifies the command that should run inside container.
    args: ["-c", "while true; do date > /opt/time/time-check.log; sleep $TIME_FREQ;done"]

    volumeMounts:
    - name: log
      mountPath: /opt/time

## -- Mount emptyDir volume. This volume will run until the lifetime of the POD. The volume and all data inside it will be permanently deleted when the POD is deleted.
  volumes:
  - name: log
    emptyDir: {}

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
