
# Command to create secret ad-hoc:
## -- kubectl create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123 -- this creates secrets in base64 encoded format

apiVersion: v1
kind: Secret
metadata: 
  name: db-secret
data:
  DB_Host: base64-encoded-value