
#We have deployed a new pod called secure-pod and a service called secure-service. Incoming or Outgoing connections to this pod are not working.
#Troubleshoot why this is happening.

#Make sure that incoming connection from the pod webapp-color are successful.


#Important: Don't delete any current objects deployed.


## In this case, both PODS are running. We only need to enable traffic flow from POD webapp-color to POD secure-pod.
## This is achieved by creating a Network Policy.

## In a Network Policy, you can define rules to allow traffic flow between PODs

## Refer to K8 Documentation to get complete YAML format for Network Policy
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-net
spec:
  podSelector:
    mathcLabels:
      run: secure-pod

  policyTypes:
  - Ingress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: webapp-color

    ports:
    - protocol: TCP
      port: 80
