## -- Create Persistent Volume for wordpress-mysql deployment

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
spec:
  accessModes:
  - ReadWriteMany

  capacity:
    storage: 1Gi

## -- If path needs to be NFS, add this attribute.
  storageClassName: nfs

  nfs:
## -- No info about the server name was given in the challenge questions on Udemy CKAD course  
    server: nfs01 
    path: "/mysql"