## -- Persistent Volume Claim for mysql deployment

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  accessModes:
  - ReadWriteMany

  resources:
    requests:
      storage: 1Gi

  storageClassName: nfs