## -- Persistent Volume Claim for wordpress deployment

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
spec:
  accessModes:
  - ReadWriteMany

  resources:
    requests:
      storage: 1Gi

  storageClassName: nfs