
## -- Command: kubectl create service nodeport --node-port=31004 wordpress --tcp=80:80 (--tcp=<port>:<targetPort>)

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 31004